config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'

  resources :movies do
    resources :reviews
  end

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  resources :users
  resource :session
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer" >
    <p>
        Copyright &copy; <%= Time.now.year %> <%= link_to 'VadimBrodsky', 'https://www.vadimbrodsky.com'  %>
    </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
    <div id="masthead">
        <h1><%= link_to 'Flix', root_path %></h1>

        <nav>
            <p>
                <% if current_user %>
                    <%= link_to current_user.name, current_user %>
                    <%= link_to 'Account Settings', edit_user_path(current_user), class: 'button' %>
                    <%= link_to 'Sign Out', session_path, method: :delete, class: 'button' %>
                <% else %>
                    <%= link_to 'Sign Up', signup_path, class: 'button' %>
                    <%= link_to 'Sign In', signin_path, class: 'button' %>
                <% end %>
            </p>
        </nav>
    </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
    <nav>
        <ul>
            <li class="all-movies"><%= link_to 'All Movies', movies_path, class: 'button' %></li>
            <% if current_user_admin? %>
            <li class="create-movie"><%= link_to 'Add New Movie', new_movie_path, class: 'button' %></li>
            <% end %>
        </ul>
    </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flix - a better IMDB</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div id="wrapper">

        <%= render 'layouts/flashes' %>

        <div id="container">
            <section id="sidebar">
                <%= render 'layouts/sidebar' %>
            </section>
            <section id="content">
                <%= yield %>
            </section>
        </div>
    </div>

    <%= render 'layouts/footer' %>
</body>
</html>